name: Tests
on:
  workflow_dispatch:
  push:
    branches:
      - testing
      - 'test-**'
    paths:
      - 'deb-get'

 # pull_request:

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  Tests:
    strategy:
      matrix:
        os: [ubuntu-latest, debian-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && export DEBIAN_FRONTEND=noninteractive
          sudo apt-get -y install --no-install-recommends jq curl shellcheck file
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          ./tests/01test-deb-get-is-installed.sh
          ./tests/02test-install-apps.sh
          ./tests/05test-deb-get-list.sh

      # Creates file "$/files.json", among others
      #- name: Gather files changed
      #  uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
      #  with:
      #    fileOutput: 'json'

      # For verification
      #- name: Show files changed
      #  run: cat $HOME/files.json

# list artifacts
# upload artifacts ?
